### ISSUE TITLE
Error in building the c extension

### ISSUE THREAD

**Issue by AlexXsh** [deu439/BOF#1]
I tried to run your code on Mac OS X, but I got the following error when I built the c extension:

sor/solver.c:5:10: fatal error: 'malloc.h' file not found

I checked the **solver.c** file, and I found the `#include <malloc.h>`. But it seems like it doesn't work. Is this error caused by Mac OS X system? Which operation system did you use?

**Comment by deu439** [comment]
It seems that [malloc.h is deprecated and the function malloc() is defined in stdlib.h](https://stackoverflow.com/questions/56463049/should-mac-osx-have-a-malloc-h-file). I updated the code, removing all occurences of #include<malloc.h>. You can try to build it again.

I use arch linux, where the compilation works correctly.

**Comment by AlexXsh** [comment]
It works. Then I got this error: 
sor/solver.c:74:34: error: implicit declaration of function 'memalign' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

**Comment by deu439** [comment]
I updated the code once again, replacing any deprecated code. You can try it now. There is not much more I can do, since I don't have access to a Mac OS machine.

**Comment by deu439** [comment]
Issue fixed by commit 807013c.
